tasks:
  - init: |
      echo init
    command: |
      sudo apt-get install -y hugo
      url=$(gp url)
      hugo server -b 1313-${url##*/} --appendPort=false
ports:
  - port: 1313
    onOpen: open-browser