baseURL: 'https://www.varrnijo.com'
languageCode: en-us
title: VarrniJÓ
theme: agency
publishDir: public
params:
  name: Your name
  description: Your description
  custom_css: []
  custom_js: []
  favicon: favicon1.ico
  disableFonts: false
  error404:
    heading: Page couldn't be found
    text: 'Please visit [this page](/)'
  navigation:
    logo: logo.png
    services: Tudnivalók
    portfolio: Galéria
    about: Tanfolyamok
    team: Rólam
    contact: Kapcsolat
  hero:
    title: VARRÓTANFOLYAMOK GYEREKEKNEK és FELNŐTTEKNEK - a siker garantált!
    subtitle: VarrniJÓ Stúdió és Tanoda
    buttonText: részletek
  services:
    enable: true
    title: Tudnivalók
    subtitle:
    row:
      - list:
          - icon: fa-child
            title: Gyerek tanfolyamok
            description: >-
              A gyerek tanfolyamokat 8 éves kortól ajánljuk egészen 16 éves korig. Minden tanfolyam 4x2 órás., min. 5, max. 8 fővel indul. 
              Folytatási lehetőség biztosított. Jelentkezők függvényében szoktunk korcsoport bontást csinálni, 
              de nyugodtan jöhetnek vegyesen (8 és 14-15 évesek együtt), mivel olyan sűrű a program egy-egy tanfolyamon, 
              hogy nem szokott gondot okozni. Minden alkalommal elkészítünk egy jól használható, szép terméket.
              

            url: '#'
          - icon: fa-user
            title: Felnőtt tanfolyamok
            description: >-
              Kezdő tanfolyam 4x3 óra, min. létszám 5 fő, max. 8 fő. 
              Egy kis elmélet után megtanuljuk a varrógépek biztonságos kezelését, alap varrástípusokkal, 
              széleldolgozó technikákkal ismerkedünk, megtanuljuk a szabás alapjait, 
              a Burda újság használatát és minden alkalommal elkészítünk egy-egy készterméket. 
              (Tolltartó, neszeszer, táska, szoknya vagy felsőrész). Amennyiben a csoport szeretné, 
              folytatási lehetőségként haladó tanfolyamot is szervezünk.

            url: '#'
          - icon: fa-calendar
            title: Nyári táborok gyerekeknek
            description: >-
              Minden nyáron rendezünk gyerekeknek nyári napközis délelőtti tábort. 
              Min. 5 fő, max. 8 fő. Korosztály: 8-15 éves korig. Minden nap 9-13 óráig várjuk a gyerekeket. 
              Azért szeretjük a nyári táborokat, mert itt lehetőség nyílik nagyobb volumenű dolgokat is elkészíteni,
              (Pl. strandtáska, nyári ruha, hűtőtáska, rajzmappa, stb.) Minden, ami a jó nyári szünethez kell!
              Több idő jut saját elképzelések, tervezések megvalósítására is. 
              Ellátás: kiadós uzsonnával készülünk.

            url: '#'
          - icon: fa-cogs
            title: Kell-e saját varrógép?
            description: >-
              Nem kell, a tanfolyamainkon minden résztvevőnek biztosítunk profi, sebességállítási 
              lehetőséggel ellátott varrógépet, de egy idő után lehet hozni saját varrógépet is, 
              amit segítünk megtanulni használni. Igény esetén tanácsot adunk, milyen gépet 
              érdemes vásárolni otthoni használatra.

            url: '#'
          - icon: fa-leaf
            title: Alapanyagok
            description: >-
              A felsőruházati termékeket jó minőségű, természetes szálú
              alapanyagokból készítjük ügyelve arra, hogy könnyen varrható
              legyen és csinos, kényelmes viseletet biztosítson. A
              kiegészítőknél, kellékeknél is igyekszünk jó minőségű, tartós
              anyagokat használni.
            url: '#'
          - icon: fa-scissors
            title: Szükséges eszközök
            description: >-
              A tanfolyamokon minden szükséges eszközt, gépet, hozzávalót biztosítunk. 
              Amit érdemes hozni: füzetet jegyzetelni (felnőtt tanfolyamokra), zárható kulacsban innivalót 
              és egy kis rágcsát (aki igényli).

            url: '#'
  portfolio:
    enable: true
    title: Galéria
    subtitle:

    modal:
      client: Client
      date: Date
      category: Category
      buttonText: Close project
  about:
    enable: true
    title: Tanfolyamok
    subtitle: Várunk szeretettel programjainkon!
    endpoint: Gyere<br>próbáld<br>ki!
    events:
      - img: helyseg.jpg
        title: AJÁNDÉKUTALVÁNY
        description: Névre szóló, 1 évig érvényes ajándékutalványok rendelhetők. Bővebb információ az info@varrnijo.com címen!

      - img: DSC_0192.JPG
        title: ÚJ GYEREK varrótábor I. turnus HAMAROSAN 
        description: 2026. nyarán hétfőtől péntekig 9-13 óráig, gyerek varrótábor indul kezdőknek 8-15 éves korig. Minden alkalommal egy csodaszép, büszkén használható, saját kezűleg megvarrt termékkel gazdagodhatnak. 
        Mellette biztos varrótudást szerezhetnek profi gépeinken. 
        Ára 65.000,-Ft (mindent szükséges hozzávalót és uzsonnát tartalmaz). Jelentkezés és bővebb információ az info@varrnijo.com címen!

      - img: varrotanf.JPG
        #date: March 2011
        title: ÚJ GYEREK varrótábor II. turnus HAMAROSAN
        description: 2026. nyarán hétfőtől péntekig 9-13 óráig, gyerek varrótábor indul kezdőknek 8-15 éves korig. Minden alkalommal egy csodaszép, büszkén használható, saját kezűleg megvarrt termékkel gazdagodhatnak. 
        Mellette biztos varrótudást szerezhetnek profi gépeinken. 
        Ára 65.000,-Ft (mindent szükséges hozzávalót és uzsonnát tartalmaz). Jelentkezés és bővebb információ az info@varrnijo.com címen!

      - img: DSC_0353.JPG
        #date: March 2011
        title: GYEREK KEZDŐ VARRÓTANFOLYAM 8 éves kortól
        description: 2026. őszétől, 4 alkalmas kezdő varrótanfolyam indul.Minden alkalommal egy csodaszép, büszkén használható, saját kezűleg megvarrt termékkel gazdagodhatnak. 
        Mellette biztos varrótudást szerezhetnek profi gépeinken. 
        Ára 45.000,-Ft (mindent tartalmaz). Jelentkezés és bővebb információ az info@varrnijo.com címen!

      - img: textilfesto.JPG
        #date: December 2012
        title: Felnőtt kezdő varrótanfolyam 16 éves kortól
        description: "HAMAROSAN. Jelentkezés és bővebb információ az info@varrnijo.com címen!"
  team:
    enable: true
    title: Rólam
    description: >-
      Ahogy teltek az évek és a gyermekeim elérték azt a kort, amikor biztonságosan kipróbálhatták a 
      varrógéppel varrást, nagyon hamar összeállt egy csapat 7-8 éves gyerek, akikkel elindítottuk az 
      első GYEREK varrótanfolyamokat. A fő szempont a biztos alapok megtanítása mellett az volt, 
      hogy minden alkalommal  egy olyan szép és sokáig használható termék készüljön el, ami növeli a 
      gyerekek önbizalmát, kreativitását és MINDENKI sikerélményekkel gazdagabban távozzon egy-egy alkalom után. 
      Ezután nem volt megállás, egyre több gyerek csatlakozott és alkotott szebbnél szebb táskákat, tolltartókat, 
      szoknyákat, pólókat, majd ahogy nőttek és fejlődtek, egyre komolyabb dolgokat is készítettünk 
      (pl. örök sláger kapucnis pulóvert, tréning nadrágot, nyári ruhát, fürdőruhát, stb.) 
      Érdemes a VarrniJÓ Stúdió facebook oldalán megnézegetni a képeket az eddigi csoportok elkészült darabjairól.
      Mindenki nagy kedvencei lettek az adventi karácsonyi ajándékkészítő alkalmak, ahol igazi kis családdá 
      formálódtak a csoportok. 
      Az évek során kifejlesztettünk egy olyan gyerekeknek szóló komplex tananyagot és tanítási módszert, 
      ami jól használható gyakorlati tudást, nagyfokú önbizalmat és sikerélményeket eredményez.
      Emellett persze a felnőtteknek is kínáltunk minden szinten tanfolyamokat, kezdő, haladó, majd klub szinten 
      alkottunk együtt.
      Tanfolyamainkon profi, sebesség állítási lehetőséggel ellátott varrógépeken dolgozunk, ami lehetővé teszi a 
      gyerekek és kezdők számára is a biztonságos varrógéphasználatot.
      Jelen célkitűzéseink közé tartozik, hogy minél több helyre eljuttassuk tanfolyamainkat, 
      ezért megalapítottuk a VarrniJó Tanodát, hogy kibővítsük gyerekeknek és felnőtteknek szóló programjainkat.
      A tanfolyamokra 8 éves kortól várunk minden lelkes, alkotni vágyó diákot, akik szeretnének egy családias, baráti csapat 
      tagjai lenni, ahol a közös alkotásban mindenki meglelheti saját kreativitását és szerezhet életreszóló, hasznos tudást, 
      sikerélményeket. 
      Továbbá 16 éves kortól várjuk szeretettel felnőtt csoportjainkba a lelkes érdeklődőket, illetve patchwork klubunkba a már 
      varrni tudókat is kortól függetlenül. 


    members:
      - img: dori.jpg
        name: Papp Dorottya
        position: >-
          Ruhaipari mérnök, szerkesztő-modellező, tanár, a ’93-as Nemzetközi
          Burda Varróverseny európa bajnoki I. helyezettje
        bio: >-
          A főiskola elvégzése után számos divattervező mellett dolgoztam
          modellezőként, majd ezzel párhuzamosan kezdtem el hobbi
          varrótanfolyamokat tartani felnőtteknek, édesanyámmal közösen
          működtetett iskolánkban. 2008-tól két gyermekemmel voltam otthon,
          ami idő alatt új impulzusok értek és megszületett bennem a VarrniJó Stúdió ötlete, 
          ahol kreatív alkotó csomagok mellett varrótanfolyamokat tartottunk. 
          Az első pár évben Siptár Réka textilművész, divattervező, a Siptár márka alapítója 
          és vezetője, a ’93-as Burda varróverseny III. helyezettje segítette munkámat. 
          Gyönyörű, egyedi díszítéseivel gazdagította csomagjaink tartalmát és részt vett tanfolyamaink szervezésében is.

        social:
          - - fa-twitter
            - '#'
          - - fa-facebook
            - '#'
          - - fa-linkedin
            - '#'

  clients_list:
    enable: false
  clients:
    - logo: envato.jpg
      link: '#'
    - logo: designmodo.jpg
      link: '#'
    - logo: themeforest.jpg
      link: '#'
    - logo: creative-market.jpg
      link: '#'
  contact:
    enable: true
    title: Kapcsolat
    address: 1114, Budapest Eszék utca 14/b. 1-es kapucsengő    info@varrnijo.com
    phone: +36 70 940 7195
    subtitle: 'Üzenet:'
    buttonText: Mehet
    email: info@varrnijo.com
    form:
      name:
        text: Neved *
        warning: Please enter your name.
      email:
        text: Email címed *
        warning: Please enter your email address.
      phone:
        text: Telefonszám *
        warning: Please enter your phone number.
      message:
        text: Üzenet *
        warning: Please enter a message.
  footer:
    enable: true
    copyright: Published under the Apache License 2.0.
    social:
      - icon: fa-twitter
        link: '#'
      - icon: fa-facebook
        link: 'https://www.facebook.com/VarrniJÓ-Stúdió-253448031848840/'
      - icon: fa-linkedin
        link: '#'
    quicklinks:
      - text: Privacy Policy
        link: '#'
      - text: Terms of Use
        link: '#'
