baseURL: 'http://www.varrnijo.com'
languageCode: en-us
title: VarrniJÓ
theme: agency
publishDir: public
params:
  name: Your name
  description: Your description
  custom_css: []
  custom_js: []
  favicon: favicon1.ico
  disableFonts: false
  error404:
    heading: Page couldn't be found
    text: 'Please visit [this page](/)'
  navigation:
    logo: logo.png
    services: Tudnivalók
    portfolio: Termékek
    about: Tanfolyamok
    team: Rólunk
    contact: Kapcsolat
  hero:
    title: VARRÓTANFOLYAMOK és VARRD MEG MAGAD kreatív szettek egyedi SIPTÁR díszítésekkel
    subtitle: VarrniJÓ
    buttonText: részletek
  services:
    enable: true
    title: Tudnivalók
    subtitle:
    row:
      - list:
          - icon: fa-female
            title: Mérettáblázat
            description: >-
              NŐI S/M MÉRET Mellbőség: 84-96 cm, Derékbőség: 66-78 cm,
              Csípőbőség:90-102 cm
              NŐI L/XL MÉRET Mellbőség:100-116 cm, Derékbőség: 82-94 cm, CSípőbőség: 102-110 cm
              NŐI EGYMÉRETES FAZONOK: Mellbőség: 84-104 cm, Derékbőség: 66-86 cm, Csípőbőség: 90-110 cm

            url: '#'
          - icon: fa-question
            title: Kiknek ajánljuk
            description: >-
              Mindenkinek, aki szeret varrni, illetve aki szeretné kipróbálni
              magát ezen a területen. Azoknak, akik nem szeretnek vagy nincs
              lehetőségük, idejük szabásmintát készíteni, anyagot vásárolni,
              szabni, de szeretnek varrni és saját készítésű ruhákban járni.
              Kreatív szettjeink tökéletesek ajándéknak is varrni tudó
              szeretteinknek.
            url: '#'
          - icon: fa-archive
            title: Kreatív szettek tartalma
            description: >-
              Kiszabott, előkészített alkatrészek. A különleges gépeket igénylő
              vagy nehezebb műveleteket előre elkészítjük (pl. gomblyukak, alja
              eldolgozások). Díszítéshez szükséges, előkészített minták.
              Szükséges kellékek: gumik, kötözők, szalagok, cérnák, stb. Leírás,
              részletes útmutató az elkészítéshez hasznos tippekkel,
              tanácsokkal.
            url: '#'
          - icon: fa-battery-2
            title: Nehézségi fokok
            description: >-
              Mindegyik termékünk alap varrásismerettel rendelkezőknek, követve
              a leírások pontos sorrendjét, egyszerűen megvarrható. A még
              teljesen kezdőknek pedig közös varrásainkon nyújtunk segítséget,
              ahol ők is elkészíthetik a kiválasztott termékeket.
            url: '#'
          - icon: fa-leaf
            title: Alapanyagok
            description: >-
              A felsőruházati termékeket jó minőségű, természetes szálú
              alapanyagokból készítjük ügyelve arra, hogy könnyen varrható
              legyen és csinos, kényelmes viseletet biztosítson. A
              kiegészítőknél, kellékeknél is igyekszünk jó minőségű, tartós
              anyagokat használni.
            url: '#'
          - icon: fa-cut
            title: Szükséges eszközök
            description: >-
              Varrógép, olló, gombostű, minden mást tartalmaz a csomag. Ha nem
              rendelkezel alap eszközökkel, rendeld meg az összeválogatott, jó
              minőségű eszköz csomagunkat, amiben megtalálsz mindent, amire
              szükséged lehet.
            url: '#'
  portfolio:
    enable: true
    title: Varrd meg magad termékek
    subtitle:

    modal:
      client: Client
      date: Date
      category: Category
      buttonText: Close project
  about:
    enable: true
    title: Tanfolyamok
    subtitle: Várunk szeretettel programjainkon!
    endpoint: Gyere<br>próbáld<br>ki!
    events:
      - img: helyseg.jpg
        title: ÚJ Intenzív felnőtt DÉLELŐTTI varrótanfolyam indul Alleenál 
        description: 2022.június 20-21-22. hétfőtől szerdáig 10-13 óráig, 3 alkalmas kezdő varrótanfolyam indul.Biztos varrótudás, alap varrástípusok, széleldolgozások, szegések és egy szabadon választható VarrniJÓ termék elkészítése. Ára 35.000,-Ft. Jelentkezés és bővebb információ a info@varrnijo.com címen!

      - img: DSC_0192.JPG
        title: ÚJ ÚJ ÚJ KEZDŐ GYEREK varrótanfolyam INDUL Alleenál 
        description: 2022.szeptemberi kezdéssel, 4 alkalmas gyerek varrótanfolyam indul teljesen kezdő szinttől 8 éves kortól. Minden alkalommal egy csodaszép, büszkén mutogatható, saját kezűleg megvarrt termékkel gazdagodhatnak (párna, tolltartó, táska, póló). Mellette biztos varrótudást szerezhetnek profi gépeinken. Ára 32.000,-Ft (mindent tartalmaz). Jelentkezés és bővebb információ az info@varrnijo.com címen!

      - img: varrotanf.JPG
        #date: March 2011
        title: Nyári intenzív kezdő felnőtt varrótanfolyam
        description: 2022.augusztus 22-23-24. hétfőtől szerdáig 10-13 óráig, 3 alkalmas kezdő varrótanfolyam indul.Biztos varrótudás, alap varrástípusok, széleldolgozások, szegések és egy szabadon választható VarrniJÓ termék elkészítése. Ára 35.000,-Ft. Jelentkezés és bővebb információ a info@varrnijo.com címen!

      - img: DSC_0353.JPG
        #date: March 2011
        title: ÚJ FELNŐTT DÉLUTÁNI KEZDŐ VARRÓTANFOLYAM INDUL
        description: 2022.október 10, 17, 24. hétfőnként 17-20 óráig, 3 alkalmas kezdő varrótanfolyam indul.Biztos varrótudás, alap varrástípusok, széleldolgozások, szegések és egy szabadon választható VarrniJÓ termék elkészítése. Ára 35.000,-Ft. Jelentkezés és bővebb információ a info@varrnijo.com címen!

      - img: textilfesto.JPG
        #date: December 2012
        title: KLUB felnőtt
        description: "2022.szeptemberétől heti 1x 17-20 óráig, Burda újság segítségével mindenki tetszőleges ruhadarabot szab és varr szakmai segítséggel hozott anyagból. Ára 30.000,-Ft. Jelentkezés és bővebb információ a info@varrnijo.com címen!"
  team:
    enable: true
    title: Rólunk
    subtitle: A VarrniJÓ alapítói
    description: >-
      Másfél évtizedes varrótanfolyamos munkám során nagyon sok varrni szerető emberrel találkoztam,
      akik teljesen kezdőként, nagy lelkesedéssel és szorgalommal eljutottak arra a szintre, hogy otthon,
      önállóan is képesek alkotni, maguknak és családjuknak megvarrni a megálmodott ruhadarabokat, kiegészítőket.
      Azonban sok olyan tanítványom is volt, akik az órákon ügyesen és lelkesen készítettek el mindent,
      viszont otthon, egyedül nem álltak neki varrni, annak ellenére, hogy minden szükséges eszközük meg
      volt hozzá. Mikor megkérdeztem, miért van ez így, sokan azt felelték, hogy nem szeretnek szabni,
      nincs akkora helyük, asztaluk, hogy kiterítsék a szabáshoz az anyagot, félnek, hogy rosszul szabják ki az alkatrészeket,
      nem tudnak szabásmintát készíteni, vagy éppen nincsen ötletük, hogy mit, milyen anyagból varrjanak…
      egyszóval macerás az egész, pedig varrni nagyon szeretnének.
      Másrészről azt látom, akár magamon is, hogy az emberek sokkal nehezebben köteleződnek el egy hosszabb
      tanfolyam mellett, szeretik, ha egy-egy alkalom alatt látványos sikereket érhetnek el, és egyre többen
      választják az ALKOTÁST kikapcsolódásra, feltöltődésre a hétköznapokban is.
      Így született meg a VarrniJÓ ötlete, ahol igyekszünk kiszolgálni azokat is, akik otthon szeretnének egyszerű,
      de nagyon csinos, mutatós ruhákat, kiegészítőket varrni maguknak és családjuknak.
      A rendelhető termékek mellett szeretnénk az ún. KÖZÖS VARRÁSOKON lehetőséget adni a jó hangulatban végezhető
      alkotó kikapcsolódásra, ahol még a varrni nem tudó, bizonytalan vagy esetleg otthoni varrógéppel nem rendelkezők
      is sikerélményt szerezhetnek a varrás terén.

    members:
      - img: dori.jpg
        name: Papp Dorottya
        position: >-
          Ruhaipari mérnök, szerkesztő-modellező, tanár, a ’93-as Nemzetközi
          Burda Varróverseny európa bajnoki I. helyezettje
        bio: >-
          A főiskola elvégzése után számos divattervező mellett dolgoztam
          modellezőként, majd ezzel párhuzamosan kezdtem el hobbi
          varrótanfolyamokat tartani felnőtteknek, édesanyámmal közösen
          működtetett iskolánkban. 2008-tól két gyermekemmel voltam otthon,
          ami idő alatt új impulzusok értek és megszületett bennem a VarrniJó
          Stúdió “kreatív szettek” és “közös varrások” ötlete. Ehhez hívtam
          segítségül Siptár Rékát, akit a fent említett Burda Varróversenyen
          ismertem meg, ahol ő is dobogós helyezést ért el, és a méltán híres
          Siptár márka megalkotója, vezetője. Ő felel a VarrniJó termékek
          csodálatos díszítéseiért.
        social:
          - - fa-twitter
            - '#'
          - - fa-facebook
            - '#'
          - - fa-linkedin
            - '#'
      - img: reka.jpg
        name: Siptár Réka
        position: >-
          Textilművész, ruhatervező, interior designer, a ’93-as Nemzetközi
          Burda Varróverseny európa bajnoki III. helyezettje, a Siptár és az
          eSeR márkák megalapítója
        bio: >-
          25 éve foglalkozom ruhák tervezésével és megvalósításával, mely ruhák
          erős karakterük miatt brandé nőtték ki magukat. Egy évvel ezelőtt
          kezdtem az általam kikisérletezett textil mintázások technikáját
          tanítani, s miután Dóri megkeresett a VarrniJÓ ötletével, úgy gondolom
          kitűnő párosítás a ruhák varrása alkalmával egy egyszerűbb technikai
          megoldással színessé és egyedivé varázsolni a megalkotott darabokat.
          Ebben szeretnék segítséget nyújtani, hogy minél többen
          megtapasztalhassák az alkotás színes örömét
        social:
          - - fa-twitter
            - '#'
          - - fa-facebook
            - '#'
          - - fa-linkedin
            - '#'
  clients_list:
    enable: false
  clients:
    - logo: envato.jpg
      link: '#'
    - logo: designmodo.jpg
      link: '#'
    - logo: themeforest.jpg
      link: '#'
    - logo: creative-market.jpg
      link: '#'
  contact:
    enable: true
    title: Kapcsolat
    address: 1114, Budapest Eszék utca 14/b. 1-es kapucsengő    info@varrnijo.com
    phone: +36 70 940 7195
    subtitle: 'Üzenet:'
    buttonText: Mehet
    email: info@varrnijo.com
    form:
      name:
        text: Neved *
        warning: Please enter your name.
      email:
        text: Email címed *
        warning: Please enter your email address.
      phone:
        text: Telefonszám *
        warning: Please enter your phone number.
      message:
        text: Üzenet *
        warning: Please enter a message.
  footer:
    enable: true
    copyright: Published under the Apache License 2.0.
    social:
      - icon: fa-twitter
        link: '#'
      - icon: fa-facebook
        link: 'https://www.facebook.com/VarrniJÓ-Stúdió-253448031848840/'
      - icon: fa-linkedin
        link: '#'
    quicklinks:
      - text: Privacy Policy
        link: '#'
      - text: Terms of Use
        link: '#'
