name: Deploy Hugo Site

on:
  push:
    branches:
      - hugo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout hugo branch
        uses: actions/checkout@v4
        with:
          ref: hugo

      - name: Setup git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch master branch
        run: git fetch origin master:refs/remotes/origin/master

      - name: Build Hugo site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/public:/output \
            -e HUGO_WATCH=false \
            jojomi/hugo:0.34
          sudo chown -R $USER:$USER public


      - name: Deploy to master branch
        run: |
          git worktree add -B master deploy origin/master
          cp -r public/* deploy/
          cd deploy
          git add --all
          git commit -m "Publishing [skip ci]" || echo "No changes to commit"
          git push origin master
